"""Tests for brief composer + has_critical."""
from __future__ import annotations
import os
import sys
from datetime import datetime, timezone

sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

from funnel_analytics_agent.sources.base import MetricSample, SourceReport
from funnel_analytics_agent.brief import compose_brief, has_critical


def _fake_report(source: str, metrics: list[MetricSample] | None = None,
                 error: str | None = None) -> SourceReport:
    return SourceReport(
        source=source,
        fetched_at=datetime.now(timezone.utc),
        metrics=metrics or [],
        error=error,
    )


def test_empty_reports_renders_skeleton():
    text = compose_brief([])
    assert "Morning Brief" in text
    assert "Generated by funnel-analytics-agent" in text


def test_critical_section_appears_first():
    crit = MetricSample(name="x", value=1, severity="critical", note="db down")
    info = MetricSample(name="y", value=2, severity="info", note="ok")
    text = compose_brief([_fake_report("vercel", [crit, info])])
    assert text.index("🚨 Critical") < text.index("📊 Metrics by source")
    assert "db down" in text


def test_warnings_separate_from_alerts():
    a = MetricSample(name="a", value=1, severity="alert", note="alert msg")
    w = MetricSample(name="b", value=2, severity="warn", note="warn msg")
    text = compose_brief([_fake_report("vercel", [a, w])])
    assert "❗ Alerts" in text and "alert msg" in text
    assert "🟡 Warnings" in text and "warn msg" in text


def test_failed_source_listed_at_bottom():
    text = compose_brief([_fake_report("vercel", error="API down")])
    assert "Sources unavailable" in text
    assert "API down" in text


def test_has_critical_true_for_critical():
    r = _fake_report("x", [MetricSample(name="m", value=1, severity="critical")])
    assert has_critical([r]) is True


def test_has_critical_true_for_alert():
    r = _fake_report("x", [MetricSample(name="m", value=1, severity="alert")])
    assert has_critical([r]) is True


def test_has_critical_false_for_warn_only():
    r = _fake_report("x", [MetricSample(name="m", value=1, severity="warn")])
    assert has_critical([r]) is False


def test_has_critical_false_for_empty():
    assert has_critical([_fake_report("x")]) is False


def test_delta_pct_renders_with_sign():
    m = MetricSample(name="m", value=100, baseline=50, delta_pct=100.0,
                     severity="info", note="2x baseline")
    text = compose_brief([_fake_report("v", [m])])
    assert "+100.0%" in text


def test_delta_pct_negative_no_double_sign():
    m = MetricSample(name="m", value=10, baseline=20, delta_pct=-50.0,
                     severity="info", note="halved")
    text = compose_brief([_fake_report("v", [m])])
    assert "-50.0%" in text
