"""Compose a daily morning-brief markdown from all source reports.

Output structure:
    # Morning Brief — YYYY-MM-DD

    🚨 Critical alerts (if any)
    🟡 Warnings  (if any)
    📊 All metrics by source
    ⚠️ Sources unavailable (if any)

The brief is meant to be read in 30 seconds over coffee. Surface
abnormalities first; raw metrics second; failures last.
"""
from __future__ import annotations
from datetime import datetime, timezone
from .sources.base import SourceReport, MetricSample


SEVERITY_RANK = {"critical": 0, "alert": 1, "warn": 2, "info": 3}
SEVERITY_ICON = {"critical": "🚨", "alert": "❗", "warn": "🟡", "info": "·"}


def compose_brief(reports: list[SourceReport], *,
                  title: str | None = None,
                  summary: str | None = None) -> str:
    """Render a list of SourceReports as one markdown brief.

    Optional `summary` is a pre-computed Claude narrative (see summarizer.py)
    that gets rendered as the second section, before any details. Pass None
    or empty string to skip.
    """
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    title = title or f"Morning Brief — {now}"

    out: list[str] = [f"# {title}", ""]

    if summary:
        out += ["## 🧠 Summary", "", summary.strip(), ""]

    # Collect all metrics with their source
    flat: list[tuple[str, MetricSample]] = []
    for r in reports:
        for m in r.metrics:
            flat.append((r.source, m))

    crit = [(s, m) for s, m in flat if m.severity == "critical"]
    alerts = [(s, m) for s, m in flat if m.severity == "alert"]
    warns = [(s, m) for s, m in flat if m.severity == "warn"]

    if crit:
        out += ["## 🚨 Critical", ""]
        for s, m in crit:
            out.append(f"- **[{s}]** {m.note}")
        out.append("")
    if alerts:
        out += ["## ❗ Alerts", ""]
        for s, m in alerts:
            out.append(f"- **[{s}]** {m.note}")
        out.append("")
    if warns:
        out += ["## 🟡 Warnings", ""]
        for s, m in warns:
            out.append(f"- **[{s}]** {m.note}")
        out.append("")

    # Then per-source dump
    out += ["## 📊 Metrics by source", ""]
    for r in sorted(reports, key=lambda r: r.source):
        if r.error:
            continue
        out.append(f"### {r.source}")
        if not r.metrics:
            out.append("_(no metrics)_")
            out.append("")
            continue
        for m in r.metrics:
            icon = SEVERITY_ICON.get(m.severity, "·")
            line = f"- {icon} `{m.name}` = **{m.value}**"
            if m.delta_pct is not None:
                sign = "+" if m.delta_pct >= 0 else ""
                line += f" ({sign}{m.delta_pct:.1f}% vs baseline)"
            if m.note:
                line += f" — {m.note}"
            out.append(line)
        out.append("")

    # Failures last
    failed = [r for r in reports if r.error]
    if failed:
        out += ["## ⚠️ Sources unavailable", ""]
        for r in failed:
            out.append(f"- **{r.source}** — {r.error}")
        out.append("")

    out += ["---",
            f"_Generated by funnel-analytics-agent at {now}_"]

    return "\n".join(out)


def has_critical(reports: list[SourceReport]) -> bool:
    """Return True if any metric is critical or alert severity. Used by the
    real-time alert mode to decide whether to ping Telegram/Slack."""
    for r in reports:
        for m in r.metrics:
            if m.severity in ("critical", "alert"):
                return True
    return False
